name: Continuous Integration

on:
  push:
  release:
    types:
      - "published"

jobs:
  ci-linux:
    name: CI Linux
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build on Linux
        run: |
          sudo apt-get install gcc-avr binutils-avr avr-libc -y
          make -j
        shell: bash
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: hshb-nametag.hex
          path: build/hshb-nametag.hex
      - name: Upload release
        if: ${{ github.event_name == 'release' }}
        uses: alexellis/upload-assets@0.4.0
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["build/hshb-nametag.hex"]'
